// components/ChessDashboard/constants.js

export const EVERGREEN_SAN = [
  "e4",
  "e5",
  "Nf3",
  "Nc6",
  "Bc4",
  "Bc5",
  "b4",
  "Bxb4",
  "c3",
  "Ba5",
  "d4",
  "exd4",
  "O-O",
  "d3",
  "Qb3",
  "Qf6",
  "e5",
  "Qg6",
  "Re1",
  "Nge7",
  "Ba3",
  "b5",
  "Qxb5",
  "Rb8",
  "Qa4",
  "Bb6",
  "Nbd2",
  "Bb7",
  "Ne4",
  "Qf5",
  "Bxd3",
  "Qh5",
  "Nf6+",
  "gxf6",
  "exf6",
  "Rg8",
  "Rad1",
  "Qxf3",
  "Rxe7+",
  "Nxe7",
  "Qxd7+",
  "Kxd7",
  "Bf5+",
  "Ke8",
  "Bd7+",
  "Kf8",
  "Bxe7#",
];

export const COMMENTARY = {
  0: "King's pawn opening — the classical start.",
  2: "Knight develops, attacking the pawn.",
  4: "Italian Game: bishop takes aim at f7.",
  6: "The Evans Gambit begins.",
  10: "White strikes the centre.",
  12: "Kingside castling completed.",
  14: "Pressure builds on f7.",
  16: "Space advantage gained.",
  18: "Rook occupies the open file.",
  22: "Queen enters aggressively.",
  28: "Knight centralizes.",
  32: "Brilliant sacrifice.",
  38: "Rook sacrifice!",
  40: "Legendary queen sacrifice.",
  46: "Checkmate. The Evergreen Game ends.",
};

export const SPRITE_COL = {
  k: 0,
  q: 1,
  r: 2,
  b: 3,
  n: 4,
  p: 5,
};

export const FILES = ["a", "b", "c", "d", "e", "f", "g", "h"];
