export const INITIAL_POSITION = [
  { piece: "♜", square: "a8", color: "black" },
  { piece: "♞", square: "b8", color: "black" },
  { piece: "♝", square: "c8", color: "black" },
  { piece: "♛", square: "d8", color: "black" },
  { piece: "♚", square: "e8", color: "black" },
  { piece: "♝", square: "f8", color: "black" },
  { piece: "♞", square: "g8", color: "black" },
  { piece: "♜", square: "h8", color: "black" },
  { piece: "♟", square: "a7", color: "black" },
  { piece: "♟", square: "b7", color: "black" },
  { piece: "♟", square: "c7", color: "black" },
  { piece: "♟", square: "d7", color: "black" },
  { piece: "♟", square: "e7", color: "black" },
  { piece: "♟", square: "f7", color: "black" },
  { piece: "♟", square: "g7", color: "black" },
  { piece: "♟", square: "h7", color: "black" },
  { piece: "♙", square: "a2", color: "white" },
  { piece: "♙", square: "b2", color: "white" },
  { piece: "♙", square: "c2", color: "white" },
  { piece: "♙", square: "d2", color: "white" },
  { piece: "♙", square: "e2", color: "white" },
  { piece: "♙", square: "f2", color: "white" },
  { piece: "♙", square: "g2", color: "white" },
  { piece: "♙", square: "h2", color: "white" },
  { piece: "♖", square: "a1", color: "white" },
  { piece: "♘", square: "b1", color: "white" },
  { piece: "♗", square: "c1", color: "white" },
  { piece: "♕", square: "d1", color: "white" },
  { piece: "♔", square: "e1", color: "white" },
  { piece: "♗", square: "f1", color: "white" },
  { piece: "♘", square: "g1", color: "white" },
  { piece: "♖", square: "h1", color: "white" },
];

export const AUTOPLAY_MOVES = [
  { from: "e2", to: "e4" },
  { from: "e7", to: "e5" },
  { from: "g1", to: "f3" },
  { from: "b8", to: "c6" },
  { from: "f1", to: "c4" },
  { from: "f8", to: "c5" },
];
